//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basic_Prophecy_Market.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basic_Prophecy_Market.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest.
        /// </summary>
        internal static string League {
            get {
                return ResourceManager.GetString("League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Dishonourable Death,Hyrri&apos;s Bite,Hyrri&apos;s Demise
        ///A Forest of False Idols,Araku Tiki,Ngamahu Tiki
        ///A Rift in Time,Timeclasp,Timetwist
        ///A Vision of Ice and Fire,Heatshiver,Frostferno
        ///Agony at Dusk,Dusktoe,Duskblight
        ///Ancient Doom,Doomfletch,Doomfletch&apos;s Prism
        ///Battle Hardened,Iron Heart,The Iron Fortress
        ///Black Devotion,Geofri&apos;s Baptism,Geofri&apos;s Devotion
        ///Blind Faith,The Ignomon,The Effigon
        ///Blinding Light,Eclipse Solaris,Corona Solaris
        ///Burning Dread,Dreadarc,Dreadsurge
        ///Cold Blooded Fury,Bloodboil,Winter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProphecyRecipes {
            get {
                return ResourceManager.GetString("ProphecyRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string SampleSize {
            get {
                return ResourceManager.GetString("SampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Anima Stone,,Primordial Might,,Primordial Harmony,,Primordial Eminence,,
        ///Arborix,,Grelwood Shank,,Beltimber Blade,,Orb of Fusing,Currency,
        ///Orb of Fusing,,Light of Lunaris,Not Corrupted,Shade of Solaris,Not Corrupted,Orb of Fusing,Currency,
        ///Kingmaker,,Soul Taker,Not Corrupted,Heartbreaker,Not Corrupted,Orb of Fusing,Currency,
        ///Kingmaker,&quot;Shaped, Not Corrupted&quot;,Soul Taker,&quot;Shaped, Not Corrupted&quot;,Heartbreaker,&quot;Shaped, Not Corrupted&quot;,Orb of Fusing,Currency,
        ///Kingmaker,&quot;Elder, Not Corrupted&quot;,Soul Taker,&quot;E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VendorRecipes {
            get {
                return ResourceManager.GetString("VendorRecipes", resourceCulture);
            }
        }
    }
}
